/**
 * quant_score.js — Live agent scoring brain
 *
 * AUTO-GENERATED by autoresearch/loop_hourly.js
 * Last promoted: 2026-03-22T18:35 UTC
 * Hourly experiments: 511 | val=7.188 combined=11.012
 *
 * This file is the best hourly signal candidate promoted to live use.
 * DO NOT edit manually — it will be overwritten on next improvement.
 * Source: autoresearch/candidate_hourly.js
 */

'use strict';

function ema(prices, period) {
  const k = 2 / (period + 1);
  let val = prices[0];
  for (let i = 1; i < prices.length; i++) val = prices[i] * k + val * (1 - k);
  return val;
}

function sma(prices, period) {
  const slice = prices.slice(-period);
  return slice.reduce((s, p) => s + p, 0) / slice.length;
}

function realizedVol(prices, period) {
  const n = Math.min(period, prices.length - 1);
  let sum = 0;
  for (let i = prices.length - n; i < prices.length; i++) {
    const r = Math.log(prices[i] / prices[i - 1]);
    sum += r * r;
  }
  return Math.sqrt(sum / n);
}

function zScore(arr) {
  const n = arr.length;
  const mean = arr.reduce((s, v) => s + v, 0) / n;
  const std  = Math.sqrt(arr.reduce((s, v) => s + (v - mean) ** 2, 0) / n);
  return std > 0 ? (arr[n - 1] - mean) / std : 0;
}

function scoreToken(data) {
  const { prices, volumes, highs, lows, opens, btcPrices } = data;
  const n  = prices.length;
  const bN = (btcPrices || []).length;
  if (n < 20) return null;  // insufficient history — signal unknown, not neutral

  // ── Trend filter: 4h close above 20-SMA ──────────────────────
  const sma20 = sma(prices, 20); // returns scalar
  const trendFilter = prices[n-1] > sma20 ? 1 : 0.5;

  // ── Relative strength vs BTC (7d) — requires 169 bars ───────
  const has7d = n >= 169 && bN >= 169;
  const tokenRet7d = has7d ? (prices[n-1] - prices[n-169]) / prices[n-169] : 0;
  const btcRet7d   = has7d ? (btcPrices[bN-1] - btcPrices[bN-169]) / btcPrices[bN-169] : 0;
  const relStr7d   = tokenRet7d - btcRet7d;

  // ── Relative strength vs BTC (4h) ───────────────────────────
  const tokenRet4h = n >= 5 ? (prices[n-1] - prices[n-5]) / prices[n-5] : 0;
  const btcRet4h   = bN >= 5 ? (btcPrices[bN-1] - btcPrices[bN-5]) / btcPrices[bN-5] : 0;
  const relStr4h   = tokenRet4h - btcRet4h;

  // ── Volume direction ─────────────────────────────────────────
  const vol4h  = volumes.slice(-4).reduce((s, v) => s + v, 0) / 4;
  const vol48h = volumes.slice(-48).reduce((s, v) => s + v, 0) / 48;
  const vol24h = volumes.slice(-24).reduce((s, v) => s + v, 0) / 24;
  const volBurst = vol4h / (vol48h || 1);
  const dir4h    = tokenRet4h > 0 ? 1 : tokenRet4h < 0 ? -1 : 0;
  const volSignal = Math.tanh((volBurst - 1) * dir4h * 2);

  // ── Momentum acceleration (4h change rate) ───────────────────
  const tokenRet8h = n >= 9 ? (prices[n-5] - prices[n-9]) / prices[n-9] : 0;
  const btcRet8h   = bN >= 9 ? (btcPrices[bN-5] - btcPrices[bN-9]) / btcPrices[bN-9] : 0;
  const relAccel   = (tokenRet4h - btcRet4h) - (tokenRet8h - btcRet8h);

  // ── Range compression detection ──────────────────────────────
  const range4h = highs.slice(-4).reduce((m, h, i) => m + (h - (lows[n-4+i] ?? h)), 0) / 4;
  const range48h = highs.slice(-48).reduce((m, h, i) => m + (h - (lows[Math.max(0,n-48+i)] ?? h)), 0) / 48;
  const rangeCoil = 1 - (range4h / (range48h || range4h || 1));

  // ── Volatility regime filter (avoid chop) ─────────────────────
  const rv12h = realizedVol(prices.slice(-12));
  const rv48h = realizedVol(prices.slice(-48));
  const volRegime = rv12h > rv48h * 0.5 ? 1 : 0.7;

  // ── 1h oversold bounce detection with dynamic threshold ──────
  let oversoldBounce = 0;
  if (n >= 24) {
    const ret1h = (prices[n-1] - prices[n-2]) / prices[n-2];
    const ret1hHist = [];
    for (let i = n - 12; i < n; i++) {
      ret1hHist.push((prices[i] - prices[i-1]) / prices[i-1]);
    }
    const avg1h = ret1hHist.reduce((s, r) => s + r, 0) / ret1hHist.length;
    const std1h = Math.sqrt(ret1hHist.reduce((s, r) => s + Math.pow(r - avg1h, 2), 0) / ret1hHist.length);
    const z1h = std1h > 0 ? (ret1h - avg1h) / std1h : 0;
    const vol1h = volumes[n-1];
    const vol1hAvg = volumes.slice(-24).reduce((s, v) => s + v, 0) / 24;
    const momentumStrength = Math.abs(relStr4h) * 35;
    const adaptiveVolThreshold = 1.2 + (0.3 * Math.tanh(momentumStrength / 5));
    const volSpike = vol1h > vol1hAvg * adaptiveVolThreshold ? 1 : 0;
    const dynamicThreshold = -1.5 + (momentumStrength * 0.15);
    oversoldBounce = z1h < dynamicThreshold && volSpike && relStr4h > 0 ? 0.22 : 0;
  }

  // ── 4h close pullback from recent 4h high (coil breakout) ────
  let bounceSignal = 0;
  if (n >= 24) {
    const high4h = Math.max(...highs.slice(-4));
    const pullbackRatio = (high4h - prices[n-1]) / (high4h || 1);
    const volumeConfirm = vol4h > vol24h ? 1 : 0.5;
    const coilBreakout = pullbackRatio > 0.01 && pullbackRatio < 0.05 && relStr4h > 0 ? 1 : 0;
    const decayFilter = Math.exp(-0.1 * (n % 4));
    bounceSignal = coilBreakout * decayFilter * volumeConfirm;
  }

  // ── Combined score [-1, +1] ──────────────────────────────────
  const score = (Math.tanh(relStr7d * 5) * 0.33
              + Math.tanh(relStr4h * 35) * 0.26
              + volSignal * 0.17
              + Math.tanh(relAccel * 50) * 0.10
              + Math.tanh(rangeCoil * 5) * 0.08
              + bounceSignal * 0.06
              + oversoldBounce) * volRegime * trendFilter;

  return Math.max(-1, Math.min(1, score));
}

module.exports = { scoreToken };

// ── Public API ───────────────────────────────────────────────────────────────
// scoreTokenHourly: used by trending_entry.js and position_monitor.js
// Accepts { prices, volumes, highs, lows, btcPrices } → score in [0, 1]
if (typeof module !== 'undefined') {
  module.exports = { scoreTokenHourly: typeof scoreToken !== 'undefined' ? scoreToken : (exports.scoreToken || (() => 0)) };
}
